--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.435.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022. 02. 16. 12:04:40
-- Server version: 10.4.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS project;

CREATE DATABASE project
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE project;

--
-- Create table `instruments`
--
CREATE TABLE instruments (
  id INT(11) NOT NULL AUTO_INCREMENT,
  instrument_name VARCHAR(255) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `category`
--
CREATE TABLE category (
  id INT(11) NOT NULL AUTO_INCREMENT,
  category VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 16,
AVG_ROW_LENGTH = 1092,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `artist`
--
CREATE TABLE artist (
  id INT(11) NOT NULL AUTO_INCREMENT,
  szuletese DATE DEFAULT NULL,
  born_age INT(11) DEFAULT NULL,
  death_age INT(11) DEFAULT NULL,
  leiras VARCHAR(255) DEFAULT NULL,
  category_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `uploaded_music`
--
CREATE TABLE uploaded_music (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) DEFAULT NULL,
  embed VARCHAR(255) DEFAULT NULL,
  genre_id INT(11) DEFAULT NULL,
  instrument_id INT(11) DEFAULT NULL,
  artist_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE uploaded_music 
  ADD CONSTRAINT FK_uploaded_music_artist_id FOREIGN KEY (artist_id)
    REFERENCES artist(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE uploaded_music 
  ADD CONSTRAINT FK_uploaded_music_category_id FOREIGN KEY (genre_id)
    REFERENCES category(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE uploaded_music 
  ADD CONSTRAINT FK_uploaded_music_instruments_id FOREIGN KEY (instrument_id)
    REFERENCES instruments(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `user`
--
CREATE TABLE user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) DEFAULT NULL,
  fullname VARCHAR(255) DEFAULT NULL,
  profile_img_url VARCHAR(255) DEFAULT NULL,
  favorite_instrument INT(11) DEFAULT NULL,
  favorite_category INT(11) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `liked_post`
--
CREATE TABLE liked_post (
  id INT(11) NOT NULL AUTO_INCREMENT,
  date DATE DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  music_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE liked_post 
  ADD CONSTRAINT FK_liked_post_uploaded_music_id FOREIGN KEY (music_id)
    REFERENCES uploaded_music(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE liked_post 
  ADD CONSTRAINT FK_liked_post_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `comments`
--
CREATE TABLE comments (
  id INT(11) NOT NULL AUTO_INCREMENT,
  date DATE DEFAULT NULL,
  comment VARCHAR(255) DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  page_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE comments 
  ADD CONSTRAINT FK_comments_uploaded_music_id FOREIGN KEY (page_id)
    REFERENCES uploaded_music(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE comments 
  ADD CONSTRAINT FK_comments_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table instruments
--
INSERT INTO instruments VALUES
(1, 'Gitár', 'guitar.png'),
(2, 'Furulya', 'flute.png'),
(3, 'Elektromos gitár', 'electric-guitar.png'),
(4, 'Zongora', 'piano.png'),
(5, 'Hegedű', 'violin.png');

-- 
-- Dumping data for table category
--
INSERT INTO category VALUES
(1, 'Afrikai'),
(2, 'Ázsiai'),
(3, 'Avantgárd'),
(4, 'Blues'),
(5, 'Komédia'),
(6, 'Country'),
(7, 'Elektronikus'),
(8, 'Népi'),
(9, 'Hip-hop zene'),
(10, 'Jazz'),
(11, 'Latin'),
(12, 'Pop'),
(13, 'R&B'),
(14, 'Rock'),
(15, 'Klasszikus');

-- 
-- Dumping data for table artist
--
-- Table project.artist does not contain any data (it is empty)

-- 
-- Dumping data for table user
--
-- Table project.user does not contain any data (it is empty)

-- 
-- Dumping data for table uploaded_music
--
-- Table project.uploaded_music does not contain any data (it is empty)

-- 
-- Dumping data for table liked_post
--
-- Table project.liked_post does not contain any data (it is empty)

-- 
-- Dumping data for table comments
--
-- Table project.comments does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;